name: Docker Build/Publish Image
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: swierzewskibartosz
      DOCKER_IMAGE: angular_spa
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Docker Login
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Run build Angular
        if: success()
        run: |
          docker build --tag swierzewskibartosz/angular_spa:latest .
          docker push swierzewskibartosz/angular_spa:latest
